import type { Deck } from "../src/types.ts";

const deck: Deck = {
  id: "urdu-phrases",
  title: "Urdu: everyday phrases",
  order: 0,
  blurb: "Common phrases for learning the language — greetings to emergencies",
  section: "urdu",
  cards: [
    // Greetings
    {
      id: "ur-001",
      source: "urdu greetings",
      type: "concept",
      front: "How do you say 'hello' in Urdu?",
      back: "سلام — salaam",
      explanation:
        "The short everyday greeting, from the fuller assalamu alaikum. Respond with the same word.",
    },
    {
      id: "ur-002",
      source: "urdu greetings",
      type: "concept",
      front: "How do you say 'goodbye' in Urdu?",
      back: "خدا حافظ — khuda hafiz",
      explanation: "Literally 'God be your protector'. The standard leave-taking in Pakistan.",
    },
    {
      id: "ur-003",
      source: "urdu greetings",
      type: "concept",
      front: "How do you say 'good morning' in Urdu?",
      back: "صبح بخیر — subah bakhair",
      explanation:
        "Used until late morning. For the evening there's a matching phrase with 'shaam'.",
    },
    {
      id: "ur-004",
      source: "urdu greetings",
      type: "concept",
      front: "How do you say 'good evening' in Urdu?",
      back: "شام بخیر — shaam bakhair",
      explanation: "The evening counterpart of 'subah bakhair', said after sunset.",
    },
    {
      id: "ur-005",
      source: "urdu greetings",
      type: "concept",
      front: "How do you ask 'how are you?' politely in Urdu?",
      back: "آپ کیسے ہیں؟ — aap kaise hain?",
      explanation: "'Aap' is the polite 'you'; use this with strangers and elders.",
    },
    {
      id: "ur-006",
      source: "urdu greetings",
      type: "concept",
      front: "How do you ask 'how are you?' casually in Urdu?",
      back: "تم کیسے ہو؟ — tum kaise ho?",
      explanation: "'Tum' is the informal 'you', for friends and people your own age.",
    },
    {
      id: "ur-007",
      source: "urdu greetings",
      type: "concept",
      front: "How do you say 'I'm fine, thank you' in Urdu?",
      back: "میں ٹھیک ہوں، شکریہ — main theek hoon, shukriya",
      explanation: "The standard reply to 'aap kaise hain?'. 'Theek' means fine or okay.",
    },
    {
      id: "ur-008",
      source: "urdu greetings",
      type: "concept",
      front: "How do you say 'see you later' in Urdu?",
      back: "پھر ملیں گے — phir milenge",
      explanation: "Literally 'we will meet again'. A warm, common way to part.",
    },
    {
      id: "ur-009",
      source: "urdu greetings",
      type: "concept",
      front: "How do you say 'nice to meet you' in Urdu?",
      back: "آپ سے مل کر خوشی ہوئی — aap se mil kar khushi hui",
      explanation: "Said when meeting someone for the first time; 'khushi' is happiness.",
    },
    {
      id: "ur-010",
      source: "urdu greetings",
      type: "concept",
      front: "How do you say 'welcome' in Urdu?",
      back: "خوش آمدید — khush aamdeed",
      explanation: "Literally 'happy arrival'. Used to welcome guests.",
    },

    // Politeness & apologies
    {
      id: "ur-011",
      source: "urdu politeness",
      type: "concept",
      front: "How do you say 'thank you' in Urdu?",
      back: "شکریہ — shukriya",
      explanation:
        "The everyday thank-you. Say 'bohat shukriya' for a stronger 'thank you very much'.",
    },
    {
      id: "ur-012",
      source: "urdu politeness",
      type: "concept",
      front: "How do you say 'thank you very much' in Urdu?",
      back: "بہت شکریہ — bohat shukriya",
      explanation: "'Bohat' means very or a lot, so this is a warmer, more emphatic thanks.",
    },
    {
      id: "ur-013",
      source: "urdu politeness",
      type: "concept",
      front: "How do you say 'please' in Urdu?",
      back: "برائے مہربانی — baraye meharbani",
      explanation: "Literally 'for kindness'. Often shortened to just 'meharbani'.",
    },
    {
      id: "ur-014",
      source: "urdu politeness",
      type: "concept",
      front: "How do you say 'sorry' in Urdu?",
      back: "معاف کیجیے — maaf kijiye",
      explanation: "A polite apology, formed from 'maaf' (forgiven) and the polite verb form.",
    },
    {
      id: "ur-015",
      source: "urdu politeness",
      type: "concept",
      front: "How do you say 'excuse me' in Urdu?",
      back: "معذرت — maazrat",
      explanation: "Use it to get attention or interrupt politely, e.g. before asking directions.",
    },
    {
      id: "ur-016",
      source: "urdu politeness",
      type: "concept",
      front: "How do you say 'you're welcome' in Urdu?",
      back: "کوئی بات نہیں — koi baat nahin",
      explanation: "Literally 'it's nothing'. The natural reply to 'shukriya'.",
    },
    {
      id: "ur-017",
      source: "urdu politeness",
      type: "concept",
      front: "How do you say 'no problem' in Urdu?",
      back: "کوئی مسئلہ نہیں — koi masla nahin",
      explanation: "Reassures that something isn't a problem; 'masla' is problem.",
    },
    {
      id: "ur-018",
      source: "urdu politeness",
      type: "concept",
      front: "How do you say 'it's my fault' in Urdu?",
      back: "میری غلطی ہے — meri ghalti hai",
      explanation: "'Ghalti' is mistake or fault. Handy for owning up to an error.",
    },
    {
      id: "ur-019",
      source: "urdu politeness",
      type: "concept",
      front: "How do you say 'I didn't mean that' in Urdu?",
      back: "میرا یہ مطلب نہیں تھا — mera yeh matlab nahin tha",
      explanation: "Softens a misunderstood remark; 'matlab' means meaning or intention.",
    },
    {
      id: "ur-020",
      source: "urdu politeness",
      type: "concept",
      front: "How do you say 'please forgive me' in Urdu?",
      back: "مجھے معاف کر دیجیے — mujhe maaf kar dijiye",
      explanation: "A stronger, more heartfelt apology than the plain 'maaf kijiye'.",
    },

    // Introductions
    {
      id: "ur-021",
      source: "urdu introductions",
      type: "concept",
      front: "How do you ask 'what is your name?' in Urdu?",
      back: "آپ کا نام کیا ہے؟ — aap ka naam kya hai?",
      explanation: "Polite form with 'aap'. Informally you'd hear 'tumhara naam kya hai?'.",
    },
    {
      id: "ur-022",
      source: "urdu introductions",
      type: "concept",
      front: "How do you say 'my name is...' in Urdu?",
      back: "میرا نام ... ہے — mera naam ... hai",
      explanation: "Fill in your name where the dots are, e.g. 'mera naam Ali hai'.",
    },
    {
      id: "ur-023",
      source: "urdu introductions",
      type: "concept",
      front: "How do you say 'I am from Pakistan' in Urdu?",
      back: "میں پاکستان سے ہوں — main Pakistan se hoon",
      explanation: "Replace 'Pakistan' with any country or city to say where you're from.",
    },
    {
      id: "ur-024",
      source: "urdu introductions",
      type: "concept",
      front: "How do you ask 'where are you from?' in Urdu?",
      back: "آپ کہاں سے ہیں؟ — aap kahan se hain?",
      explanation: "'Kahan' is where, so this literally asks 'from where are you?'.",
    },
    {
      id: "ur-025",
      source: "urdu introductions",
      type: "concept",
      front: "How do you say 'I am learning Urdu' in Urdu?",
      back: "میں اردو سیکھ رہا ہوں — main Urdu seekh raha hoon",
      explanation:
        "'Seekh raha hoon' is the ongoing 'I am learning'. A female speaker says 'seekh rahi hoon'.",
    },
    {
      id: "ur-026",
      source: "urdu introductions",
      type: "concept",
      front: "How do you ask 'do you speak English?' in Urdu?",
      back: "کیا آپ انگریزی بولتے ہیں؟ — kya aap angrezi bolte hain?",
      explanation: "'Bolte hain' is the polite 'you speak'; for a woman it's 'bolti hain'.",
    },
    {
      id: "ur-027",
      source: "urdu introductions",
      type: "concept",
      front: "How do you say 'I don't speak Urdu well' in Urdu?",
      back: "میں اردو اچھی طرح نہیں بولتا — main Urdu achhi tarah nahin bolta",
      explanation: "'Achhi tarah' means well; a female speaker ends with 'bolti'.",
    },
    {
      id: "ur-028",
      source: "urdu introductions",
      type: "concept",
      front: "How do you say 'I understand a little' in Urdu?",
      back: "مجھے تھوڑی سمجھ آتی ہے — mujhe thori samajh aati hai",
      explanation: "Reassures the other person to keep talking slowly; 'samajh' is understanding.",
    },
    {
      id: "ur-029",
      source: "urdu introductions",
      type: "concept",
      front: "How do you ask 'how old are you?' in Urdu?",
      back: "آپ کی عمر کتنی ہے؟ — aap ki umar kitni hai?",
      explanation: "'Umar' is age and 'kitni' is how much, so literally 'how much is your age?'.",
    },
    {
      id: "ur-030",
      source: "urdu introductions",
      type: "concept",
      front: "How do you say 'I am twenty years old' in Urdu?",
      back: "میری عمر بیس سال ہے — meri umar bees saal hai",
      explanation: "The pattern is 'meri umar <number> saal hai' — swap the number for your age.",
    },

    // Basic questions
    {
      id: "ur-031",
      source: "urdu questions",
      type: "concept",
      front: "How do you ask 'what is this?' in Urdu?",
      back: "یہ کیا ہے؟ — yeh kya hai?",
      explanation: "The single most useful phrase for pointing at things while learning.",
    },
    {
      id: "ur-032",
      source: "urdu questions",
      type: "concept",
      front: "How do you say 'why?' in Urdu?",
      back: "کیوں؟ — kyun?",
      explanation: "A one-word question, exactly like English.",
    },
    {
      id: "ur-033",
      source: "urdu questions",
      type: "concept",
      front: "How do you say 'when?' in Urdu?",
      back: "کب؟ — kab?",
      explanation: "One word; add a phrase after it for 'when does...'.",
    },
    {
      id: "ur-034",
      source: "urdu questions",
      type: "concept",
      front: "How do you say 'where?' in Urdu?",
      back: "کہاں؟ — kahan?",
      explanation: "Use it on its own, or in 'kahan hai?' for 'where is...'.",
    },
    {
      id: "ur-035",
      source: "urdu questions",
      type: "concept",
      front: "How do you say 'how?' in Urdu?",
      back: "کیسے؟ — kaise?",
      explanation: "Also the start of 'how much' questions when combined with other words.",
    },
    {
      id: "ur-036",
      source: "urdu questions",
      type: "concept",
      front: "How do you ask 'how much?' or 'how many?' in Urdu?",
      back: "کتنا؟ — kitna?",
      explanation: "For asking prices, quantities, or time: 'kitna baj raha hai?'.",
    },
    {
      id: "ur-037",
      source: "urdu questions",
      type: "concept",
      front: "How do you ask 'which one?' in Urdu?",
      back: "کون سا؟ — kaun sa?",
      explanation: "'Kaun' is who/which; 'sa' agrees with a masculine noun.",
    },
    {
      id: "ur-038",
      source: "urdu questions",
      type: "concept",
      front: "How do you say 'who?' in Urdu?",
      back: "کون؟ — kaun?",
      explanation: "One word. 'Kaun hai?' means 'who is it?'.",
    },
    {
      id: "ur-039",
      source: "urdu questions",
      type: "concept",
      front: "How do you ask 'do you understand?' in Urdu?",
      back: "کیا آپ سمجھ گئے؟ — kya aap samajh gaye?",
      explanation: "'Samajh gaye' is 'understood'; great for checking comprehension.",
    },
    {
      id: "ur-040",
      source: "urdu questions",
      type: "concept",
      front: "How do you ask 'can you help me?' in Urdu?",
      back: "کیا آپ میری مدد کر سکتے ہیں؟ — kya aap meri madad kar sakte hain?",
      explanation: "'Madad' is help. Drop the 'kya' for a more direct request.",
    },

    // Numbers & counting
    {
      id: "ur-041",
      source: "urdu numbers",
      type: "concept",
      front: "How do you say 'one' in Urdu?",
      back: "ایک — aik",
      explanation: "The counting form; the same word also works as 'a' or 'an'.",
    },
    {
      id: "ur-042",
      source: "urdu numbers",
      type: "concept",
      front: "How do you say 'two' in Urdu?",
      back: "دو — do",
      explanation: "Identical in sound to English 'do', which makes it easy to remember.",
    },
    {
      id: "ur-043",
      source: "urdu numbers",
      type: "concept",
      front: "How do you say 'three' in Urdu?",
      back: "تین — teen",
      explanation: "Rhymes with English 'teen', as in thirteen.",
    },
    {
      id: "ur-044",
      source: "urdu numbers",
      type: "concept",
      front: "How do you say 'four' in Urdu?",
      back: "چار — chaar",
      explanation: "Almost the same as the Hindi numeral word and easy to pronounce.",
    },
    {
      id: "ur-045",
      source: "urdu numbers",
      type: "concept",
      front: "How do you say 'five' in Urdu?",
      back: "پانچ — paanch",
      explanation: "Note the nasal 'n' at the end — say 'paanch', not 'pach'.",
    },
    {
      id: "ur-046",
      source: "urdu numbers",
      type: "concept",
      front: "How do you say 'ten' in Urdu?",
      back: "دس — das",
      explanation: "The base for teens: eleven is 'giyarah', twelve is 'baarah', and so on.",
    },
    {
      id: "ur-047",
      source: "urdu numbers",
      type: "concept",
      front: "How do you say 'twenty' in Urdu?",
      back: "بیس — bees",
      explanation: "Combine it with units: twenty-one is 'ikees', twenty-two is 'baaees'.",
    },
    {
      id: "ur-048",
      source: "urdu numbers",
      type: "concept",
      front: "How do you say 'hundred' in Urdu?",
      back: "سو — sau",
      explanation: "Two hundred is 'do sau', three hundred is 'teen sau', and so on.",
    },
    {
      id: "ur-049",
      source: "urdu numbers",
      type: "concept",
      front: "How do you say 'thousand' in Urdu?",
      back: "ہزار — hazaar",
      explanation:
        "South Asian numbers group by lakhs and crores, but 'hazaar' still shows up everywhere.",
    },
    {
      id: "ur-050",
      source: "urdu numbers",
      type: "concept",
      front: "How do you say 'half' in Urdu?",
      back: "آدھا — aadha",
      explanation: "Handy at markets for quantities, like 'aadha kilo' for half a kilo.",
    },

    // Time & days
    {
      id: "ur-051",
      source: "urdu time",
      type: "concept",
      front: "How do you ask 'what time is it?' in Urdu?",
      back: "کتنا بج رہا ہے؟ — kitna baj raha hai?",
      explanation: "Literally 'how much is striking?', from 'bajna', the verb for bells striking.",
    },
    {
      id: "ur-052",
      source: "urdu time",
      type: "concept",
      front: "How do you say 'today' in Urdu?",
      back: "آج — aaj",
      explanation:
        "Pairs with 'kal' (tomorrow/yesterday) and 'parson' (day after/before tomorrow).",
    },
    {
      id: "ur-053",
      source: "urdu time",
      type: "concept",
      front: "How do you say 'tomorrow' in Urdu?",
      back: "کل — kal",
      explanation: "Beware: 'kal' also means 'yesterday' — context and verb tense tell you which.",
    },
    {
      id: "ur-054",
      source: "urdu time",
      type: "concept",
      front: "How do you say 'now' in Urdu?",
      back: "اب — ab",
      explanation: "'Abhi' (right now, in a moment) is the even more immediate cousin.",
    },
    {
      id: "ur-055",
      source: "urdu time",
      type: "concept",
      front: "How do you say 'later' in Urdu?",
      back: "بعد میں — baad mein",
      explanation: "'Baad' is 'after'; add 'mein' for 'later on'.",
    },
    {
      id: "ur-056",
      source: "urdu time",
      type: "concept",
      front: "How do you say 'in the morning' in Urdu?",
      back: "صبح — subah",
      explanation: "'Subah' is also the word for dawn itself, as in 'subah bakhair'.",
    },
    {
      id: "ur-057",
      source: "urdu time",
      type: "concept",
      front: "How do you say 'at night' in Urdu?",
      back: "رات کو — raat ko",
      explanation: "'Raat' is night and 'ko' marks the time, so it's literally 'night-at'.",
    },
    {
      id: "ur-058",
      source: "urdu time",
      type: "concept",
      front: "How do you say 'this week' in Urdu?",
      back: "اس ہفتے — is hafte",
      explanation: "'Hafta' is week; swap 'is' for 'doosre' to say 'next week'.",
    },
    {
      id: "ur-059",
      source: "urdu time",
      type: "concept",
      front: "How do you ask 'what day is it today?' in Urdu?",
      back: "آج کون سا دن ہے؟ — aaj kaun sa din hai?",
      explanation:
        "Days of the week are easy to learn in pairs: Monday is 'peer', Tuesday 'mangal'.",
    },

    // Food & drink
    {
      id: "ur-060",
      source: "urdu food",
      type: "concept",
      front: "How do you say 'water' in Urdu?",
      back: "پانی — paani",
      explanation:
        "One of the first words every visitor picks up. Ask for 'thanda paani' for cold water.",
    },
    {
      id: "ur-061",
      source: "urdu food",
      type: "concept",
      front: "How do you say 'tea' in Urdu?",
      back: "چائے — chai",
      explanation:
        "The national drink — usually milky and sweet unless you ask for 'bila chini' (no sugar).",
    },
    {
      id: "ur-062",
      source: "urdu food",
      type: "concept",
      front: "How do you say 'bread' in Urdu?",
      back: "روٹی — roti",
      explanation: "Flatbread baked in a tandoor or on a griddle — the staple at most meals.",
    },
    {
      id: "ur-063",
      source: "urdu food",
      type: "concept",
      front: "How do you say 'food' in Urdu?",
      back: "کھانا — khana",
      explanation: "Also the verb 'to eat'; 'khana khaya?' means 'have you eaten?'.",
    },
    {
      id: "ur-064",
      source: "urdu food",
      type: "concept",
      front: "How do you say 'I am hungry' in Urdu?",
      back: "مجھے بھوک لگی ہے — mujhe bhook lagi hai",
      explanation: "Literally 'hunger has struck me' — 'bhook' is hunger.",
    },
    {
      id: "ur-065",
      source: "urdu food",
      type: "concept",
      front: "How do you say 'I am thirsty' in Urdu?",
      back: "مجھے پیاس لگی ہے — mujhe pyaas lagi hai",
      explanation: "The same pattern as hunger: 'pyaas' is thirst, 'lagi hai' is 'has struck'.",
    },
    {
      id: "ur-066",
      source: "urdu food",
      type: "concept",
      front: "How do you say 'it's delicious' in Urdu?",
      back: "مزے دار ہے — mazedar hai",
      explanation: "'Maza' is taste or fun; 'mazedar' means tasty or enjoyable.",
    },
    {
      id: "ur-067",
      source: "urdu food",
      type: "concept",
      front: "How do you say 'vegetarian' in Urdu?",
      back: "سبزی خور — sabzi khor",
      explanation: "'Sabzi' is vegetable and 'khor' is eater — worth knowing at restaurants.",
    },
    {
      id: "ur-068",
      source: "urdu food",
      type: "concept",
      front: "How do you ask for the bill at a restaurant in Urdu?",
      back: "مہربانی کر کے بل دیجیے — meharbani kar ke bill dijiye",
      explanation: "Literally 'kindly give the bill'. 'Dijiye' is the polite 'please give'.",
    },

    // Shopping & bargaining
    {
      id: "ur-069",
      source: "urdu shopping",
      type: "concept",
      front: "How do you ask 'how much is this?' in Urdu?",
      back: "اس کی کتنی قیمت ہے؟ — is ki kitni qeemat hai?",
      explanation: "'Qeemat' is price; this is the standard market opener.",
    },
    {
      id: "ur-070",
      source: "urdu shopping",
      type: "concept",
      front: "How do you say 'that's too expensive' in Urdu?",
      back: "بہت مہنگا ہے — bohat mehnga hai",
      explanation: "The first half of every negotiation — 'mehnga' means expensive.",
    },
    {
      id: "ur-071",
      source: "urdu shopping",
      type: "concept",
      front: "How do you ask for a lower price in Urdu?",
      back: "تھوڑا سستا کر دیجیے — thora sasta kar dijiye",
      explanation: "Literally 'make it a little cheaper' — 'sasta' is cheap or reduced.",
    },
    {
      id: "ur-072",
      source: "urdu shopping",
      type: "concept",
      front: "How do you ask 'do you have...?' in Urdu?",
      back: "کیا آپ کے پاس ... ہے؟ — kya aap ke paas ... hai?",
      explanation: "Fill in the item, e.g. 'kya aap ke paas chai hai?' for 'do you have tea?'.",
    },
    {
      id: "ur-073",
      source: "urdu shopping",
      type: "concept",
      front: "How do you say 'I want to buy this' in Urdu?",
      back: "میں یہ خریدنا چاہتا ہوں — main yeh khareedna chahta hoon",
      explanation: "'Khareedna' is to buy; a female speaker says 'chahti hoon'.",
    },
    {
      id: "ur-074",
      source: "urdu shopping",
      type: "concept",
      front: "How do you say 'money' in Urdu?",
      back: "پیسے — paise",
      explanation: "Informal and everyday. 'Rupay' is used for rupees specifically.",
    },
    {
      id: "ur-075",
      source: "urdu shopping",
      type: "concept",
      front: "How do you ask for a discount in Urdu?",
      back: "کچھ رعایت کیجیے — kuch riayat kijiye",
      explanation: "'Riayat' is a reduction or discount; 'kuch' means a bit or some.",
    },
    {
      id: "ur-076",
      source: "urdu shopping",
      type: "concept",
      front: "How do you ask 'can I pay by card?' in Urdu?",
      back: "کیا میں کارڈ سے ادائیگی کر سکتا ہوں؟ — kya main card se adaigi kar sakta hoon?",
      explanation:
        "'Adaigi' is payment; the answer is often 'paise mein' (cash only) at small shops.",
    },
    {
      id: "ur-077",
      source: "urdu shopping",
      type: "concept",
      front: "How do you say 'market' in Urdu?",
      back: "بازار — bazaar",
      explanation: "Familiar from English — a bazaar is a market street or shopping district.",
    },

    // Directions & travel
    {
      id: "ur-078",
      source: "urdu directions",
      type: "concept",
      front: "How do you ask 'where is...?' in Urdu?",
      back: "... کہاں ہے؟ — ... kahan hai?",
      explanation: "Put the place first: 'station kahan hai?' for 'where is the station?'.",
    },
    {
      id: "ur-079",
      source: "urdu directions",
      type: "concept",
      front: "How do you say 'the station' in Urdu?",
      back: "اسٹیشن — station",
      explanation:
        "A loanword, so it's easy; the railway station is 'railway station' in Urdu too.",
    },
    {
      id: "ur-080",
      source: "urdu directions",
      type: "concept",
      front: "How do you say 'the airport' in Urdu?",
      back: "ہوائی اڈہ — hawai adda",
      explanation: "Literally 'air port'; you'll also hear 'airport' used directly.",
    },
    {
      id: "ur-081",
      source: "urdu directions",
      type: "concept",
      front: "How do you say 'left' in Urdu?",
      back: "بائیں — baen",
      explanation: "Pair it with 'muriye' (turn) in 'baen muriye' — 'turn left'.",
    },
    {
      id: "ur-082",
      source: "urdu directions",
      type: "concept",
      front: "How do you say 'right' in Urdu?",
      back: "دائیں — daen",
      explanation: "The directional opposite of 'baen'; 'daen muriye' means turn right.",
    },
    {
      id: "ur-083",
      source: "urdu directions",
      type: "concept",
      front: "How do you say 'straight ahead' in Urdu?",
      back: "سیدھا — seedha",
      explanation: "'Seedha jaiye' means 'go straight'; 'seedha' also means honest or direct.",
    },
    {
      id: "ur-084",
      source: "urdu directions",
      type: "concept",
      front: "How do you say 'far' in Urdu?",
      back: "دور — door",
      explanation:
        "The answer to 'kya door hai?' — 'is it far?' — is usually 'door hai' or 'nazdeek hai'.",
    },
    {
      id: "ur-085",
      source: "urdu directions",
      type: "concept",
      front: "How do you say 'near' in Urdu?",
      back: "قریب — qareeb",
      explanation:
        "'Qareeb' means close by; 'paas' (as in 'aap ke paas') also works for 'near you'.",
    },
    {
      id: "ur-086",
      source: "urdu directions",
      type: "concept",
      front: "How do you say 'a taxi' in Urdu?",
      back: "ٹیکسی — taxi",
      explanation: "A loanword. To hail one: 'taxi kahan milegi?' — 'where can I get a taxi?'.",
    },

    // Emergencies & health
    {
      id: "ur-087",
      source: "urdu emergencies",
      type: "concept",
      front: "How do you shout 'help!' in Urdu?",
      back: "مدد! — madad!",
      explanation: "Loud and clear: 'madad!' — the word for help all by itself.",
    },
    {
      id: "ur-088",
      source: "urdu emergencies",
      type: "concept",
      front: "How do you say 'I am lost' in Urdu?",
      back: "میں راستہ بھول گیا ہوں — main rasta bhool gaya hoon",
      explanation: "Literally 'I have forgotten the way'; a female speaker says 'bhool gayi hoon'.",
    },
    {
      id: "ur-089",
      source: "urdu emergencies",
      type: "concept",
      front: "How do you say 'call the police' in Urdu?",
      back: "پولیس کو بلائیں — police ko bulayen",
      explanation: "'Bulana' means to call or summon, and 'ko' marks the police as the target.",
    },
    {
      id: "ur-090",
      source: "urdu emergencies",
      type: "concept",
      front: "How do you say 'I need a doctor' in Urdu?",
      back: "مجھے ڈاکٹر کی ضرورت ہے — mujhe doctor ki zaroorat hai",
      explanation:
        "'Zaroorat' is need or requirement; the same pattern works for anything you need.",
    },
    {
      id: "ur-091",
      source: "urdu emergencies",
      type: "concept",
      front: "How do you say 'I am sick' in Urdu?",
      back: "میں بیمار ہوں — main beemar hoon",
      explanation: "'Beemar' is ill or unwell; the noun 'bemari' means illness.",
    },
    {
      id: "ur-092",
      source: "urdu emergencies",
      type: "concept",
      front: "How do you say 'hospital' in Urdu?",
      back: "ہسپتال — hospital",
      explanation: "A familiar loanword; the emergency room is 'emergency' there too.",
    },
    {
      id: "ur-093",
      source: "urdu emergencies",
      type: "concept",
      front: "How do you say 'medicine' in Urdu?",
      back: "دوا — dawa",
      explanation: "Also means medicine in general; the chemist's shop is the 'dawa khana'.",
    },
    {
      id: "ur-094",
      source: "urdu emergencies",
      type: "concept",
      front: "How do you say 'I have a headache' in Urdu?",
      back: "میرے سر میں درد ہے — mere sar mein dard hai",
      explanation: "Literally 'there is pain in my head' — swap 'sar' for any body part.",
    },

    // Feelings & small talk
    {
      id: "ur-095",
      source: "urdu feelings",
      type: "concept",
      front: "How do you say 'I am happy' in Urdu?",
      back: "میں خوش ہوں — main khush hoon",
      explanation: "'Khush' is happy; you'll hear it in 'khush aamdeed' (welcome) too.",
    },
    {
      id: "ur-096",
      source: "urdu feelings",
      type: "concept",
      front: "How do you say 'I am tired' in Urdu?",
      back: "میں تھکا ہوا ہوں — main thaka hua hoon",
      explanation: "A female speaker says 'main thaki hui hoon'; 'thakna' is the verb to tire.",
    },
    {
      id: "ur-097",
      source: "urdu feelings",
      type: "concept",
      front: "How do you ask 'how do you say this in Urdu?' in Urdu?",
      back: "اردو میں یہ کیسے کہتے ہیں؟ — Urdu mein yeh kaise kehte hain?",
      explanation: "The magic phrase for language learners — point at anything and ask.",
    },
    {
      id: "ur-098",
      source: "urdu feelings",
      type: "concept",
      front: "How do you ask 'what does this word mean?' in Urdu?",
      back: "اس لفظ کا کیا مطلب ہے؟ — is lafz ka kya matlab hai?",
      explanation: "'Lafz' is word and 'matlab' is meaning — the follow-up to every new word.",
    },
    {
      id: "ur-099",
      source: "urdu feelings",
      type: "concept",
      front: "How do you ask someone to speak slowly in Urdu?",
      back: "مہربانی کر کے آہستہ بولیں — meharbani kar ke aahista bolein",
      explanation:
        "'Aahista' means slowly or quietly; you'll hear it constantly in Urdu conversation.",
    },
    {
      id: "ur-100",
      source: "urdu feelings",
      type: "concept",
      front: "How do you ask someone to repeat something in Urdu?",
      back: "مہربانی کر کے دوبارہ کہیے — meharbani kar ke dobara kahiye",
      explanation: "'Dobara' means again — 'dobara kahiye' is 'please say it again'.",
    },
  ],
};

export default deck;
